### ISSUE TITLE
Error loading the plugin.

### ISSUE THREAD

**Issue by ellisgl** [SyraTechnologies/Craftcoinishv2#2]
[21:41:19 INFO]: This server is running CraftBukkit version git-Bukkit-1.7.2-R0.3-b3020jnks (MC: 1.7.2) (Implementing API version 1.7.2-R0.3)
[21:41:19 ERROR]: Could not load 'plugins/Craftcoinish-1.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:184) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at org.bukkit.craftbukkit.v1_7_R1.CraftServer.loadPlugins(CraftServer.java:350) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at org.bukkit.craftbukkit.v1_7_R1.CraftServer.<init>(CraftServer.java:312) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at net.minecraft.server.v1_7_R1.PlayerList.<init>(PlayerList.java:63) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at net.minecraft.server.v1_7_R1.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at net.minecraft.server.v1_7_R1.DedicatedServer.init(DedicatedServer.java:126) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:424) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method) ~[?:1.7.0_25]
        at java.util.zip.ZipFile.<init>(ZipFile.java:215) ~[?:1.7.0_25]
        at java.util.zip.ZipFile.<init>(ZipFile.java:145) ~[?:1.7.0_25]
        at java.util.jar.JarFile.<init>(JarFile.java:153) ~[?:1.7.0_25]
        at java.util.jar.JarFile.<init>(JarFile.java:117) ~[?:1.7.0_25]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:172) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        ... 8 more

**Comment by SyraTechnologies** [comment]
Your .jar isn't being compiled correctly. Your configuration is most likely incorrect. I used Eclipse for my maven imports.

Also make sure all dependencies for the .jar are installed and up to date through Maven.

-------- Original Message --------
Subject: [Craftcoinishv2] Error loading the plugin. (#2)

**Comment by ellisgl** [comment]
Well, it's the one I pull off the site pre-compiled.

**Comment by SyraTechnologies** [comment]
CraftCoin the website compiles their own copy. I do not keep in contact with them.

-------- Original Message --------
Subject: Re: [Craftcoinishv2] Error loading the plugin. (#2)

**Comment by ellisgl** [comment]
Ah, sorry about that then.
